version: 0.2

env:
  variables:
    ENVIRONMENT: "Value passed by CodeBuild"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm ci
      - npm install -g aws-cdk
      - cdk --version

  build:
    commands:
      - echo Synthesizing CDK template
      - mkdir -p output
      - cdk synth sle-infrastructure-$ENVIRONMENT --output output

  post_build:
    commands:
      - echo Synth complete
      - ls -la output

artifacts:
  base-directory: output
  files:
    - "*.template.json"
  discard-paths: yes